### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by artourkin**
- I have added a possibility of gathering zipped fits files.
- All the test are working fine.

### CODE REVIEW

**Comment by peshkira** [comment]
Thanks Artour!

I will inspect and probably merge it these days. Is there a reason, why there are three commits with the same messages for both fixes? Should I just merge the last ones?

cheers

**Comment by artourkin** [comment]
these were microcommits. However I dont know how to merge them on github :)

**Comment by peshkira** [comment]
Ok, I will manage them and probably squash them into two commits.
For the future, could you please write different messages, or if you need the same message, consider amending the last commit and just squash the changes into the last one.

cheers

**Comment by peshkira** [comment]
Hi!
Thanks again for your PR.

I just investigated the code. I will not merge it right now, as it is a bit messy and I will need a bit more time to clean it up. I will create a little page with some recommendation and guidelines for future PRs but here is some info, for future work, if you are still going to contribute.

**Code**
- variables and fields in java start with a lower case letter and should be in camelCase
- method names should also start with a lower case letter
- only constants should be written ALL_CAPS
- field declarations should be declared first!!!
  - then the constructors, 
  - then the public methods, then protected, then private (optional, but a good practice)
- do not check if a boolean variable is false like this if(bool == false) either invert the condition or use if (!bool) {…}
- do not use extra brackets within methods to separate code blocks. If you need this for readability, you are doing something wrong. If there is some other reason, please let me know.
- never, ever, ever leave empty catch blocks!!!

**Repo**
- Do not submit binaries within the repo (you have submitted a 70Mb zip), this just makes the repo cluttered and slow to clone. If you need the zip consider using Dropbox or something else.
- Keep the external resources needed for tests to a minimum (consider using mocks, if you need many resource files). Do you need so many xml files for the test? Shouldn't 2 or 3 be enough

I also saw some bi-directional dependencies between the Gatherer and the Controller that shouldn't exist, but I will try to fix these when I start merging.

cheers

**Comment by artourkin** [comment]
I could try to clean this mess a bit according to your guidelines =)

**Comment by peshkira** [comment]
sure any help is appreciated :+1: :)

**Comment by peshkira** [comment]
I am closing this issue now without merging it, because the new version supports this behaviour out of the box.
Also, I saw that you spawn an outside tar process in your solution, which is not really great imo for a few reasons.

1) On Windows systems there might be no tar installed
2) The supported extensions for the archives that you use are not all supported by tar
3) Spawning external processes is a task that I try to avoid always when possible as it is not always deterministic what happens.

I have solved it with an apache library. Now you can mix normal files and archives in the same directory and they will all be processed

**Pull request closed without merging**
