### PR TITLE
Bug fixing and travis CI integration

### PR DESCRIPTION
**Pull request by luis100**
It solves a bug when conflicted properties have only one value. Integrates with Travis CI and adds the build status to the README.

### CODE REVIEW

**Comment by peshkira** [comment]
Thanks guys! Amazing..

I will do some work on c3po later today and tomorrow (because I still have to release the experimental Tika support from the SPRUCE Event) and I will merge it. I am not familiar with Travis... if I merge this, will it mean that it will build this repo and the fork of openplanets as well?

cheers

**Comment by luis100** [comment]
For travis you just need to go to the https://travis-ci.org, log in with your github account and add your C3PO repository.Then, you need to make small change to README.md because it is pointing to the openplanets version of C3PO.

When you commit anything on your repository, it will build only your own repository.

cheers!

**Comment by peshkira** [comment]
That is great. The only problem I see, is @carlwilson will need to maintain his own README for openplanets/c3po everytime he pulls the changes from this repo. May be we can use only one travis for this main fork. I guess, that is something to discuss on the call

**Comment by luis100** [comment]
The small change is just to add the building status image to the readme, which is kind of cool but not essential:

http://about.travis-ci.org/docs/user/status-images/

This seems like an open issue in travis-ci:
https://github.com/travis-ci/travis-ci/issues/779

**Comment by peshkira** [comment]
I have merged this pull request manually. Thanks again.
For some reason travis doesn't pick up my repository. When I go to the travis site, it just says "Please wait while we sync from GitHub" and doesn't do anything. Is there any other setup that I should do? 

bump
@carlwilson 
@luis100

**Comment by luis100** [comment]
That happen to me once, just tried again later and it worked...

**Comment by peshkira** [comment]
The problem was that with my repository there is an additional parameter needed (?branch=master). I just added it and it worked. This could be a small pain during dev on another branch, because I/we will have to manage the README and switch this param before merging back to master. I am known for forgetting these things :laughing: 

Anyway, thanks for the PR, keep them coming :)

**Pull request merged**
